name: MsBox
version: '${project.version}'
main: me.xsenny.msbox.MsBox
api-version: 1.19
commands:
  tempban:
    description: tempban a player
  ban:
    description: ban a player permanently
  mute:
    description: mute a player permanently
  tempmute:
    description: tempmute a player
  kick:
    description: Kick a player
  report:
    description: Report a player